export const tagTypes = {
  auth: "Auth",
  otp: "Otp",
  customer: "Customer",
  csr: "CSR",
  admin: "Admin",
  common: "Common",
  settings: "Settings",
  review: "Review",
  order: "Order",
  payment: "Payment",
  meta: "Meta",
  user: "User",
  users: "Users",
  orders: "Orders",
  categories: "Categories",
  library: "Library",
  aiGeneratedImage: "AiGeneratedImage",
  messages: "Messages",
  notifications: "Notifications",

  // Quote Page
  quoteProducts: "QuoteProducts",
  quoteProduct: "QuoteProduct",
  quoteCategories: "QuoteCategories",
  quoteSizes: "QuoteSizes",
  quotes: "Quotes",

  // Shop Page
  shopCategories: "ShopCategories",
  shopProducts: "ShopProducts",
  shopProduct: "ShopProduct",
  shopProductSizes: "ShopProductSizes",
  shopProductReviews: "ShopProductReviews",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.otp,
  tagTypes.customer,
  tagTypes.csr,
  tagTypes.admin,
  tagTypes.common,
  tagTypes.settings,
  tagTypes.user,
  tagTypes.users,
  tagTypes.quote,
  tagTypes.review,
  tagTypes.order,
  tagTypes.payment,
  tagTypes.meta,
  tagTypes.orders,
  tagTypes.categories,
  tagTypes.library,
  tagTypes.aiGeneratedImage,
  tagTypes.messages,
  tagTypes.notifications,

  // Quote Page
  tagTypes.quoteProduct,
  tagTypes.quoteProducts,
  tagTypes.quoteCategories,
  tagTypes.quoteSizes,
  tagTypes.quotes,

  // Shop Page
  tagTypes.shopCategories,
  tagTypes.shopProducts,
  tagTypes.shopProduct,
  tagTypes.shopProductSizes,
  tagTypes.shopProductReviews,
];
